version: '3.8'

#Only used for development. Database will be setup differently in prod

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=LocalPassword123 # Retrieves password from .env file
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - ./init.sql:/init.sql # Copies the init sql script to the container
      - ./entrypoint.sh:/entrypoint.sh # Copies the entrypoint script to the container
      # - sqlserverdata:/var/opt/mssql # Uncomment this line and volumes to persist data
    command: ["sh", "/entrypoint.sh"] # Runs the entrypoint script on startup
    env_file:
          - .env

# volumes: 
#   sqlserverdata:
    