name: Build and Deploy .NET App

on:
  push:
    branches:
      - main  # Replace with your target branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0' # Replace with your .NET version

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the project
    - name: Build
      run: dotnet build --configuration Release --no-restore

    # Publish the application
    - name: Publish
      run: dotnet publish -c Release -o ./publish

    # Upload artifacts (Optional: useful for debugging deployment issues)
    - name: Archive published files
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-app
        path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Transfer files to the server
    - name: Deploy to Server
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_PATH: ${{ secrets.SERVER_PATH }}
      run: |
        sudo apt-get install -y rsync sshpass
        sshpass -e rsync -avz ./publish/ $SERVER_USER@$SERVER_HOST:$SERVER_PATH
